const fs = require('fs');

const d = {
  "Standard Package": { hi: "मानक पैकेज", fr: "Forfait Standard", de: "Standard-Paket", nl: "Standaard Pakket", ru: "Стандартный Пакет", ja: "スタンダードパッケージ", zh: "标准套餐", ar: "الباقة القياسية", es: "Paquete Estándar", pt: "Pacote Padrão" },
  "Comfortable 4-star accommodations, daily breakfast, standard group transport, and guided tours.": { hi: "आरामदायक 4-स्टार आवास, दैनिक नाश्ता, मानक समूह परिवहन और निर्देशित पर्यटन।", fr: "Hébergement confortable 4 étoiles, petit-déjeuner quotidien, transport de groupe standard et visites guidées.", de: "Komfortable 4-Sterne-Unterkünfte, tägliches Frühstück, Standard-Gruppentransport und geführte Touren.", nl: "Comfortabele 4-sterrenaccommodaties, dagelijks ontbijt, standaard groepsvervoer en rondleidingen.", ru: "Комфортабельное 4-звездочное размещение, ежедневный завтрак, стандартный групповой транспорт и экскурсии.", ja: "快適な4つ星の宿泊施設、毎日の朝食、標準的なグループ送迎、ガイド付きツアー。", zh: "舒适的 4 星级住宿、每日早餐、标准团体接送和带导游的游览。", ar: "إقامة مريحة 4 نجوم، إفطار يومي، نقل جماعي قياسي، وجولات إرشادية.", es: "Cómodo alojamiento de 4 estrellas, desayuno diario, transporte grupal estándar y visitas guiadas.", pt: "Acomodações confortáveis de 4 estrelas, café da manhã diário, transporte em grupo padrão e visitas guiadas." },
  "Premium Package - Honeymooners Offer": { hi: "प्रीमियम पैकेज - हनीमूनर्स ऑफर", fr: "Forfait Premium - Offre lune de miel", de: "Premium-Paket - Flitterwochen-Angebot", nl: "Premium Pakket - Aanbieding voor pasgetrouwden", ru: "Премиум-пакет - Предложение для молодоженов", ja: "プレミアムパッケージ - ハネムーンオファー", zh: "高级套餐 - 蜜月特惠", ar: "الباقة المميزة - عرض لقضاء شهر العسل", es: "Paquete Premium - Oferta para recién casados", pt: "Pacote Premium - Oferta para lua de mel" },
  "Luxury 5-star ocean-view accommodations, all meals included, private luxury chauffeur, and exclusive romantic experiences.": { hi: "लक्जरी 5-स्टार समुद्र-दृश्य आवास, सभी भोजन शामिल, निजी लक्जरी ड्राइवर, और विशेष रोमांटिक अनुभव।", fr: "Hébergement de luxe 5 étoiles avec vue sur l'océan, tous les repas inclus, chauffeur privé de luxe et expériences romantiques exclusives.", de: "Luxuriöse 5-Sterne-Unterkünfte mit Meerblick, alle Mahlzeiten inbegriffen, privater Luxus-Chauffeur und exklusive romantische Erlebnisse.", nl: "Luxe 5-sterrenaccommodaties met uitzicht op de oceaan, alle maaltijden inbegrepen, luxe privéchauffeur en exclusieve romantische ervaringen.", ru: "Роскошное 5-звездочное размещение с видом на океан, все включено, личный роскошный водитель и эксклюзивные романтические впечатления.", ja: "オーシャンビューの豪華な5つ星の宿泊施設、すべての食事、プライベートラグジュアリー運転手、独占的なロマンチックな体験。", zh: "豪华 5 星级海景住宿，含全餐，私人豪华司机和专属浪漫体验。", ar: "إقامة فاخرة 5 نجوم مطلة على المحيط، جميع الوجبات مشمولة، سائق فاخر خاص، وتجارب رومانسية حصرية.", es: "Lujoso alojamiento de 5 estrellas con vista al océano, todas las comidas incluidas, chofer de lujo privado y experiencias románticas exclusivas.", pt: "Acomodações luxuosas de 5 estrelas com vista para o mar, todas as refeições incluídas, motorista de luxo privado e experiências românticas exclusivas." },
  "Deluxe Executive Ocean Suite": { hi: "डीलक्स कार्यकारी महासागर सुइट", fr: "Suite exécutive de luxe vue mer", de: "Deluxe Executive Ocean Suite", nl: "Deluxe Executive Ocean Suite", ru: "Представительский люкс Делюкс с видом на океан", ja: "デラックスエグゼクティブオーシャンスイート", zh: "豪华行政海景套房", ar: "جناح تنفيذي ديلوكس مطل على المحيط", es: "Suite ejecutiva de lujo con vista al mar", pt: "Suíte executiva de luxo com vista para o mar" },
  "Overwater or beachfront executive suite with private plunge pool, butler service, complimentary spa voucher, and VIP lounge access.": { hi: "निजी प्लंज पूल, बटलर सेवा, मानार्थ स्पा वाउचर और वीआईपी लाउंज एक्सेस के साथ ओवरवाटर या बीचफ्रंट कार्यकारी सुइट।", fr: "Suite exécutive sur pilotis ou en bord de mer avec petite piscine privée, service de majordome, bon d'achat gratuit pour le spa et accès au salon VIP.", de: "Overwater- oder Beachfront-Executive-Suite mit privatem Tauchbecken, Butler-Service, kostenlosem Spa-Gutschein und Zugang zur VIP-Lounge.", nl: "Overwater of strand executive suite met privé dompelbad, butlerservice, gratis spavoucher en toegang tot de VIP-lounge.", ru: "Представительский люкс над водой или на берегу с собственным мини-бассейном, услугами дворецкого, бесплатным ваучером в спа-салон и доступом в VIP-зал.", ja: "プライベートプランジプール、バトラーサービス、無料のスパバウチャー、VIPラウンジへのアクセスが備わる水上またはビーチフロントのエグゼクティブスイート。", zh: "水上或海滨行政套房，配有私人小型游泳池、管家服务、免费水疗代金券和贵宾休息室使用权。", ar: "جناح تنفيذي فوق الماء أو على شاطئ البحر مع مسبح غطس خاص وخدمة الخادم الشخصي وقسيمة سبا مجانية والوصول إلى صالة كبار الشخصيات.", es: "Suite ejecutiva sobre el agua o frente a la playa con piscina privada, servicio de mayordomo, vale de spa de cortesía y acceso a la sala VIP.", pt: "Suíte executiva sobre a água ou à beira-mar com piscina privativa, serviço de mordomo, voucher de spa de cortesia e acesso ao lounge VIP." },
  "Family Multi-Room Villa Package": { hi: "परिवार मल्टी-रूम विला पैकेज", fr: "Forfait Villa Familiale Multi-Chambres", de: "Familien-Multi-Zimmer-Villenpaket", nl: "Familiepakket villa met meerdere kamers", ru: "Пакет Семейная многокомнатная вилла", ja: "ファミリーマルチルームヴィラパッケージ", zh: "家庭多房间别墅套餐", ar: "باقة فيلا عائلية متعددة الغرف", es: "Paquete de villa familiar de varias habitaciones", pt: "Pacote de vila familiar com vários quartos" },
  "Spacious 2-bedroom villa with private garden, kids club access, daily family dining credits, and private beach cabana.": { hi: "निजी उद्यान, किड्स क्लब एक्सेस, दैनिक पारिवारिक डाइनिंग क्रेडिट और निजी समुद्र तट कबाना के साथ विशाल 2-बेडरूम विला।", fr: "Spacieuse villa de 2 chambres avec jardin privé, accès au club enfants, crédits repas quotidiens en famille et cabane privée sur la plage.", de: "Geräumige Villa mit 2 Schlafzimmern, privatem Garten, Zugang zum Kinderclub, täglichem Familien-Essensguthaben und privater Strandkabine.", nl: "Ruime villa met 2 slaapkamers, privétuin, toegang tot de kinderclub, dagelijks familiedinertegoed en privécabana op het strand.", ru: "Просторная вилла с 2 спальнями, частным садом, доступом в детский клуб, ежедневными кредитами на семейное питание и частной пляжной кабинкой для переодевания.", ja: "プライベートガーデン、キッズクラブへのアクセス、毎日の家族の食事クレジット、プライベートビーチカバナを備えた広々とした2ベッドルームヴィラ。", zh: "宽敞的 2 居室别墅，设有私人花园、儿童俱乐部使用权、每日家庭餐饮积分和私人海滩小屋。", ar: "فيلا فسيحة من غرفتي نوم مع حديقة خاصة وإمكانية الدخول إلى نادي الأطفال وأرصدة طعام عائلية يومية وكابانا شاطئية خاصة.", es: "Amplia villa de 2 dormitorios con jardín privado, acceso al club infantil, créditos diarios para cenas familiares y cabaña de playa privada.", pt: "Vila espaçosa de 2 quartos com jardim privativo, acesso ao clube infantil, créditos diários de refeições em família e cabana privativa na praia." }
};

const langs = ['hi', 'fr', 'de', 'nl', 'ru', 'ja', 'zh', 'ar', 'es', 'pt'];
langs.forEach(lang => {
  const path = `src/locales/${lang}.json`;
  if (fs.existsSync(path)) {
    const data = JSON.parse(fs.readFileSync(path, 'utf8'));
    for (const [key, transMap] of Object.entries(d)) {
      if (transMap[lang]) {
        data[key] = transMap[lang];
      }
    }
    fs.writeFileSync(path, JSON.stringify(data, null, 2));
    console.log(`Fixed hotel packages in ${lang}.json`);
  }
});
