const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, 'src/locales/en.json');
const enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));

Object.assign(enData, {
  "Based on 1,480+ verified reviews": "Based on 1,480+ verified reviews",
  "Authentic Traveler Ratings": "Authentic Traveler Ratings",
  "100% Real Guest Experiences": "100% Real Guest Experiences",
  "Loved by Travelers Worldwide": "Loved by Travelers Worldwide",
  "Share Your Story": "Share Your Story",
  "Verified Social Proof": "Verified Social Proof",
  "TRAVELER PHOTOS &": "TRAVELER PHOTOS &",
  "REVIEWS": "REVIEWS",
  "Verified Guest": "Verified Guest",
  "Photos Taken By Guest": "Photos Taken By Guest",
  "No reviews found for this filter.": "No reviews found for this filter.",
  "Share Your Sri Lanka Experience": "Share Your Sri Lanka Experience",
  "Your story and photos inspire fellow luxury travelers!": "Your story and photos inspire fellow luxury travelers!",
  "Signed in as": "Signed in as",
  "Verified Guest badge will be automatically attached!": "Verified Guest badge will be automatically attached!",
  "Posting as Guest": "Posting as Guest",
  "Sign In First": "Sign In First",
  "Story Published Successfully!": "Story Published Successfully!",
  "Thank you! Your story and photos are now live on our website for travelers around the world to discover.": "Thank you! Your story and photos are now live on our website for travelers around the world to discover.",
  "Your Name": "Your Name",
  "City & Country": "City & Country",
  "Tour / Experience": "Tour / Experience",
  "Trip Category": "Trip Category",
  "Overall Rating": "Overall Rating",
  "Story Title / Headline": "Story Title / Headline",
  "Your Story & Experience": "Your Story & Experience",
  "Attach Holiday Photos": "Attach Holiday Photos",
  "Photos Attached": "Photos Attached",
  "Uploading...": "Uploading...",
  "Upload From Device": "Upload From Device",
  "OR": "OR",
  "Add": "Add",
  "Publishing Story...": "Publishing Story...",
  "Publish Verified Traveler Story": "Publish Verified Traveler Story",
  "Premier Guarantees & Travel Extras": "Premier Guarantees & Travel Extras",
  "Book with absolute confidence & 100% financial protection": "Book with absolute confidence & 100% financial protection",
  "ESSENTIAL PROTECTION &": "ESSENTIAL PROTECTION &",
  "TRAVEL EXTRAS": "TRAVEL EXTRAS",
  "ATOL #11840": "ATOL #11840",
  "ABTA Y6421": "ABTA Y6421",
  "Essential Extra & Protection": "Essential Extra & Protection",
  "Official Service & Policy standard": "Official Service & Policy standard",
  "Close & Continue": "Close & Continue",
  "Where to next?": "Where to next?",
  "For exclusive deals, tailored holiday packages, and the best of the Premier Tour Booking portfolio, add your email below.": "For exclusive deals, tailored holiday packages, and the best of the Premier Tour Booking portfolio, add your email below.",
  "You're Subscribed!": "You're Subscribed!",
  "Thank you for subscribing. Exclusive luxury offers and tailored holiday packages will be delivered to your inbox.": "Thank you for subscribing. Exclusive luxury offers and tailored holiday packages will be delivered to your inbox.",
  "Subscribe another email": "Subscribe another email",
  "Email address": "Email address",
  "SUBSCRIBE": "SUBSCRIBE",
  "Sign up": "Sign up",
  "Signing up...": "Signing up...",
  "All Reviews": "All Reviews",
  "With Photos": "With Photos",
  "Honeymoon & Couples": "Honeymoon & Couples",
  "Family Trips": "Family Trips",
  "Solo & Wellness": "Solo & Wellness",
  "Travel Dates": "Travel Dates",
  "N": "N",
  "Incredible Sri Lanka Experience!": "Incredible Sri Lanka Experience!",
  "Luxury Sri Lanka Tour": "Luxury Sri Lanka Tour",
  "Premier Tour Booking is a global travel provider offering customizable beach retreats, cultural explorations, modern flight packages, and premier car rentals since 2018. Over 120,000 travelers trust us to craft their dream itineraries.": "Premier Tour Booking is a global travel provider offering customizable beach retreats, cultural explorations, modern flight packages, and premier car rentals since 2018. Over 120,000 travelers trust us to craft their dream itineraries.",
  "Help": "Help",
  "Support Centre": "Support Centre",
  "Store Locator": "Store Locator",
  "ABTA & ATOL Bonded": "ABTA & ATOL Bonded",
  "General": "General",
  "Careers": "Careers",
  "Brochures": "Brochures",
  "Privacy Policy": "Privacy Policy",
  "Terms of Service": "Terms of Service",
  "Cookie Policy": "Cookie Policy",
  "All rights reserved.": "All rights reserved.",
  "blog": "blog",
  "Blog": "Blog",
  "Destinations": "Destinations",
  "Travel Tips": "Travel Tips",
  "Guides": "Guides",
  "e.g. Maldives, Istanbul, Santorini": "e.g. Maldives, Istanbul, Santorini",
  "e.g. London LHR, Dubai DXB": "e.g. London LHR, Dubai DXB",
  "Departure": "Departure",
  "Return": "Return",
  "3 Days": "3 Days",
  "1 Week": "1 Week",
  "2 Weeks": "2 Weeks",
  "Select Start Date": "Select Start Date",
  "Select End Date": "Select End Date",
  "Check In": "Check In",
  "Night": "Night",
  "Nights": "Nights",
  "Clear dates": "Clear dates",
  "Done": "Done"
});

fs.writeFileSync(enPath, JSON.stringify(enData, null, 2));
console.log('en.json updated successfully.');
