const fs = require('fs');
const path = require('path');

const srcLocalesDir = path.join(__dirname, '../src/locales');
const pubLocalesDir = path.join(__dirname, '../public/locales');

// Load en.json keys
const enData = JSON.parse(fs.readFileSync(path.join(srcLocalesDir, 'en.json'), 'utf8'));
const allKeys = Object.keys(enData);

// Supported languages
const langs = ['de', 'fr', 'ar', 'nl', 'ja', 'zh', 'ru', 'hi'];

// Comprehensive dictionaries for full phrases across all views
const phraseDict = {
  de: {
    "OUR LEGACY": "UNSER ERBE",
    "Our Mission & Story": "Unsere Mission & Geschichte",
    "Established 2018": "Gegründet 2018",
    "Perfecting Travel Since 2018": "Reisen perfektionieren seit 2018",
    "TRAVELER PHOTOS &": "REISEFOTOS &",
    "REVIEWS": "BEWERTUNGEN",
    "ALL REVIEWS": "ALLE BEWERTUNGEN",
    "All Reviews": "Alle Bewertungen",
    "WITH PHOTOS": "MIT FOTOS",
    "With Photos": "Mit Fotos",
    "HONEYMOON & COUPLES": "FLITTERWOCHEN & PAARE",
    "Honeymoon & Couples": "Flitterwochen & Paare",
    "FAMILY TRIPS": "FAMILIENREISEN",
    "Family Trips": "Familienreisen",
    "Solo & Wellness": "Solo & Wellness",
    "SOLO & WELLNESS": "SOLO & WELLNESS",
    "Verified Guest": "Geprüfter Gast",
    "PHOTOS TAKEN BY GUEST:": "VOM GAST GENOMMENE FOTOS:",
    "Photos Taken By Guest": "Fotos vom Gast aufgenommen",
    "Loved by Travelers Worldwide": "Von Reisenden weltweit geliebt",
    "Based on 1,480+ verified reviews": "Basierend auf 1.480+ verifizierten Bewertungen",
    "Authentic Traveler Ratings": "Authentische Reisebewertungen",
    "100% Real Guest Experiences": "100% Echte Gästeerfahrungen",
    "Share Your Story": "Teilen Sie Ihre Geschichte",
    "Verified Social Proof": "Geprüfter Social Proof",
    "Discover the World, Perfected For You": "Entdecken Sie die Welt, perfektioniert für Sie",
    "The Perfect Stay, Every Single Time": "Der perfekte Aufenthalt, jedes einzelne Mal",
    "The Perfect Flight, Every Single Time": "Der perfekte Flug, jedes einzelne Mal",
    "Exquisite Luxury, Unrestricted Paths": "Exquisiter Luxus, uneingeschränkte Pfade",
    "Check-in - Check-out": "Check-in – Check-out",
    "Check In": "Check-in",
    "Check Out": "Check-out",
    "Pick-up Date & Time": "Abholdatum & Uhrzeit",
    "Drop-off Date & Time": "Rückgabedatum & Uhrzeit",
    "Star Rating": "Sternebewertung",
    "Price Range": "Preisspanne",
    "Sort By": "Sortieren nach",
    "Filter By": "Filtern nach",
    "Search Tours": "Touren suchen",
    "Search Hotels": "Hotels suchen",
    "Search Flights": "Flüge suchen",
    "Search Car Rentals": "Mietwagen suchen",
    "View Details": "Details anzeigen",
    "Book Now": "Jetzt buchen",
    "Reserve Spot": "Platz reservieren",
    "Select Package": "Paket auswählen",
    "Custom Itinerary": "Individuelle Reiseroute",
    "Passenger Details": "Passagierdaten",
    "Contact Details": "Kontaktdaten",
    "Payment Method": "Zahlungsmethode",
    "Credit / Debit Card": "Kredit- / Debitkarte",
    "Bank Transfer": "Banküberweisung",
    "Cash on Arrival": "Barzahlung bei Ankunft",
    "Instant Confirmation": "Sofortige Bestätigung",
    "Flexible Cancellation": "Flexible Stornierung",
    "Free Cancellation": "Kostenlose Stornierung",
    "All Inclusive": "Alles inklusive",
    "Breakfast Included": "Frühstück inbegriffen",
    "Free WiFi": "Kostenloses WLAN",
    "Airport Transfer Included": "Flughafentransfer inbegriffen",
    "Private Driver & Guide": "Privater Fahrer & Reiseleiter",
    "Luxury Vehicle": "Luxusfahrzeug",
    "Air Conditioned": "Klimatisiert",
    "Verified Reviews": "Verifizierte Bewertungen",
    "Customer Support": "Kundenservice",
    "Frequently Asked Questions": "Häufig gestellte Fragen",
    "Privacy Policy": "Datenschutz-Bestimmungen",
    "Terms & Conditions": "Allgemeine Geschäftsbedingungen",
    "About Us": "Über uns",
    "Contact Us": "Kontaktieren Sie uns",
    "Home": "Startseite",
    "Tours": "Touren",
    "Hotels": "Hotels",
    "Flights": "Flüge",
    "Car Rentals": "Mietwagen",
    "Rent A Car": "Mietwagen",
    "Blog": "Blog",
    "Wishlist": "Wunschliste",
    "Dashboard": "Dashboard",
    "My Bookings": "Meine Buchungen",
    "Sign In": "Anmelden",
    "Sign Up": "Registrieren",
    "Log Out": "Abmelden",
    "Arrangement": "Arrangement",
    "Spa & Wellness": "Spa & Wellness",
    "24h Butler": "24h Butler-Service",
    "First Class": "Erste Klasse",
    "Business Class": "Business-Klasse",
    "Economy Class": "Economy-Klasse",
    "Premium Economy": "Premium Economy"
  },
  fr: {
    "OUR LEGACY": "NOTRE HÉRITAGE",
    "Our Mission & Story": "Notre Mission & Histoire",
    "Established 2018": "Fondé en 2018",
    "Perfecting Travel Since 2018": "L'Art du Voyage depuis 2018",
    "TRAVELER PHOTOS &": "PHOTOS DE VOYAGEURS &",
    "REVIEWS": "AVIS",
    "ALL REVIEWS": "TOUS LES AVIS",
    "All Reviews": "Tous les Avis",
    "WITH PHOTOS": "AVEC PHOTOS",
    "With Photos": "Avec Photos",
    "HONEYMOON & COUPLES": "LUNE DE MIEL & COUPLES",
    "Honeymoon & Couples": "Lune de Miel & Couples",
    "FAMILY TRIPS": "VOYAGES EN FAMILLE",
    "Family Trips": "Voyages en Famille",
    "Solo & Wellness": "Solo & Bien-être",
    "SOLO & WELLNESS": "SOLO & BIEN-ÊTRE",
    "Verified Guest": "Client Vérifié",
    "PHOTOS TAKEN BY GUEST:": "PHOTOS PRISES PAR LE CLIENT:",
    "Photos Taken By Guest": "Photos Prises Par Le Client",
    "Loved by Travelers Worldwide": "Aimé par les voyageurs du monde entier",
    "Based on 1,480+ verified reviews": "Basé sur plus de 1 480 avis vérifiés",
    "Authentic Traveler Ratings": "Évaluations Authentiques des Voyageurs",
    "100% Real Guest Experiences": "Expériences 100% Réelles de Nos Clients",
    "Share Your Story": "Partagez Votre Histoire",
    "Verified Social Proof": "Preuve Sociale Vérifiée",
    "Discover the World, Perfected For You": "Découvrez le monde, perfectionné pour vous",
    "The Perfect Stay, Every Single Time": "Le séjour parfait, à chaque fois",
    "The Perfect Flight, Every Single Time": "Le vol parfait, à chaque fois",
    "Exquisite Luxury, Unrestricted Paths": "Luxe exquis, chemins sans limites",
    "Check-in - Check-out": "Arrivée – Départ",
    "Check In": "Arrivée",
    "Check Out": "Départ",
    "Pick-up Date & Time": "Date et heure de prise en charge",
    "Drop-off Date & Time": "Date et heure de restitution",
    "Star Rating": "Étoiles",
    "Price Range": "Gamme de prix",
    "Sort By": "Trier par",
    "Filter By": "Filtrer par",
    "Search Tours": "Rechercher des circuits",
    "Search Hotels": "Rechercher des hôtels",
    "Search Flights": "Rechercher des vols",
    "Search Car Rentals": "Rechercher des voitures",
    "View Details": "Voir les détails",
    "Book Now": "Réserver maintenant",
    "Reserve Spot": "Réserver votre place",
    "Select Package": "Sélectionner le forfait",
    "Custom Itinerary": "Itinéraire personnalisé",
    "Passenger Details": "Détails des passagers",
    "Contact Details": "Coordonnées",
    "Payment Method": "Mode de paiement",
    "Credit / Debit Card": "Carte de crédit / débit",
    "Bank Transfer": "Virement bancaire",
    "Cash on Arrival": "Paiement à l'arrivée",
    "Instant Confirmation": "Confirmation immédiate",
    "Flexible Cancellation": "Annulation flexible",
    "Free Cancellation": "Annulation gratuite",
    "All Inclusive": "Tout compris",
    "Breakfast Included": "Petit-déjeuner inclus",
    "Free WiFi": "Wi-Fi gratuit",
    "Airport Transfer Included": "Transfert aéroport inclus",
    "Private Driver & Guide": "Chauffeur privé & Guide",
    "Luxury Vehicle": "Véhicule de luxe",
    "Air Conditioned": "Climatisé",
    "Verified Reviews": "Avis vérifiés",
    "Customer Support": "Service client",
    "Frequently Asked Questions": "Foire aux questions",
    "Privacy Policy": "Politique de confidentialité",
    "Terms & Conditions": "Conditions générales",
    "About Us": "À propos de nous",
    "Contact Us": "Contactez-nous",
    "Home": "Accueil",
    "Tours": "Circuits",
    "Hotels": "Hôtels",
    "Flights": "Vols",
    "Car Rentals": "Location de voitures",
    "Rent A Car": "Louer une voiture",
    "Blog": "Blog",
    "Wishlist": "Favoris",
    "Dashboard": "Tableau de bord",
    "My Bookings": "Mes réservations",
    "Sign In": "Connexion",
    "Sign Up": "S'inscrire",
    "Log Out": "Déconnexion",
    "Arrangement": "Formule",
    "Spa & Wellness": "Spa & Bien-être",
    "24h Butler": "Service de majordome 24h",
    "First Class": "Première Classe",
    "Business Class": "Classe Affaires",
    "Economy Class": "Classe Économique",
    "Premium Economy": "Économique Premium"
  },
  ar: {
    "OUR LEGACY": "إرثنا",
    "Our Mission & Story": "مهمتنا وقصتنا",
    "Established 2018": "تأسس عام 2018",
    "Perfecting Travel Since 2018": "إتقان السفر منذ عام 2018",
    "TRAVELER PHOTOS &": "صور المسافرين و",
    "REVIEWS": "المراجعات",
    "ALL REVIEWS": "جميع المراجعات",
    "All Reviews": "جميع المراجعات",
    "WITH PHOTOS": "مع صور",
    "With Photos": "مع صور",
    "HONEYMOON & COUPLES": "شهر العسل والأزواج",
    "Honeymoon & Couples": "شهر العسل والأزواج",
    "FAMILY TRIPS": "رحلات عائلية",
    "Family Trips": "رحلات عائلية",
    "Solo & Wellness": "فردي وعافية",
    "SOLO & WELLNESS": "فردي وعافية",
    "Verified Guest": "ضيف موثق",
    "PHOTOS TAKEN BY GUEST:": "الصور الملتقطة بواسطة الضيف:",
    "Photos Taken By Guest": "الصور الملتقطة بواسطة الضيف",
    "Loved by Travelers Worldwide": "محبوب من قبل المسافرين حول العالم",
    "Based on 1,480+ verified reviews": "بناءً على أكثر من 1480 مراجعة موثقة",
    "Authentic Traveler Ratings": "تقييمات مسافرين حقيقية",
    "100% Real Guest Experiences": "تجارب ضيوف حقيقية 100%",
    "Share Your Story": "شارك قصتك",
    "Verified Social Proof": "إثبات اجتماعي موثق",
    "Discover the World, Perfected For You": "اكتشف العالم، بمثالية مصممة لك",
    "The Perfect Stay, Every Single Time": "الإقامة المثالية، في كل مرة",
    "The Perfect Flight, Every Single Time": "الرحلة الجوية المثالية، في كل مرة",
    "Exquisite Luxury, Unrestricted Paths": "فخامة راقية، وطرق بلا حدود",
    "Check-in - Check-out": "تسجيل الوصول - تسجيل المغادرة",
    "Check In": "تسجيل الوصول",
    "Check Out": "تسجيل المغادرة",
    "Pick-up Date & Time": "تاريخ ووقت الاستلام",
    "Drop-off Date & Time": "تاريخ ووقت التسليم",
    "Star Rating": "تصنيف النجوم",
    "Price Range": "نطاق الأسعار",
    "Sort By": "ترتيب حسب",
    "Filter By": "تصفية حسب",
    "Search Tours": "البحث عن الجولات",
    "Search Hotels": "البحث عن الفنادق",
    "Search Flights": "البحث عن الرحلات الجوية",
    "Search Car Rentals": "البحث عن تأجير السيارات",
    "View Details": "عرض التفاصيل",
    "Book Now": "احجز الآن",
    "Reserve Spot": "احجز مقعدك",
    "Select Package": "اختر الباقة",
    "Custom Itinerary": "مسار رحلة مخصص",
    "Passenger Details": "بيانات الركاب",
    "Contact Details": "بيانات الاتصال",
    "Payment Method": "طريقة الدفع",
    "Credit / Debit Card": "بطاقة ائتمان / خصم",
    "Bank Transfer": "تحويل بنكي",
    "Cash on Arrival": "الدفع عند الوصول",
    "Instant Confirmation": "تأكيد فوري",
    "Flexible Cancellation": "إلغاء مرن",
    "Free Cancellation": "إلغاء مجاني",
    "All Inclusive": "شامل كلياً",
    "Breakfast Included": "الإفطار مشمول",
    "Free WiFi": "إنترنت مجاني",
    "Airport Transfer Included": "التوصيل من وإلى المطار مشمول",
    "Private Driver & Guide": "سائق وخبير سياحي خاص",
    "Luxury Vehicle": "سيارة فاخرة",
    "Air Conditioned": "مكيف الهواء",
    "Verified Reviews": "مراجعات موثقة",
    "Customer Support": "دعم العملاء",
    "Frequently Asked Questions": "الأسئلة الشائعة",
    "Privacy Policy": "سياسة الخصوصية",
    "Terms & Conditions": "الشروط والأحكام",
    "About Us": "من نحن",
    "Contact Us": "اتصل بنا",
    "Home": "الرئيسية",
    "Tours": "الجولات",
    "Hotels": "الفنادق",
    "Flights": "الطيران",
    "Car Rentals": "تأجير السيارات",
    "Rent A Car": "استئجار سيارة",
    "Blog": "المدونة",
    "Wishlist": "المفضلة",
    "Dashboard": "لوحة التحكم",
    "My Bookings": "حجوزاتي",
    "Sign In": "تسجيل الدخول",
    "Sign Up": "إنشاء حساب",
    "Log Out": "تسجيل الخروج",
    "Arrangement": "الترتيب",
    "Spa & Wellness": "سبا وعافية",
    "24h Butler": "خدمة نادل على مدار 24 ساعة",
    "First Class": "الدرجة الأولى",
    "Business Class": "درجة الأعمال",
    "Economy Class": "الدرجة السياحية",
    "Premium Economy": "الدرجة السياحية الممتازة"
  },
  nl: {
    "OUR LEGACY": "ONZE ERFENIS",
    "Our Mission & Story": "Onze Missie & Verhaal",
    "Established 2018": "Opgericht in 2018",
    "Perfecting Travel Since 2018": "Reizen Perfectioneren Sinds 2018",
    "TRAVELER PHOTOS &": "REIZIGERSFOTO'S &",
    "REVIEWS": "BEOORDELINGEN",
    "ALL REVIEWS": "ALLE BEOORDELINGEN",
    "All Reviews": "Alle Beoordelingen",
    "WITH PHOTOS": "MET FOTO'S",
    "With Photos": "Met Foto's",
    "HONEYMOON & COUPLES": "HUWELIJKSREIS & STELLES",
    "Honeymoon & Couples": "Huwelijksreis & Stelles",
    "FAMILY TRIPS": "FAMILIEREIZEN",
    "Family Trips": "Familiereizen",
    "Solo & Wellness": "Solo & Wellness",
    "SOLO & WELLNESS": "SOLO & WELLNESS",
    "Verified Guest": "Geverifieerde Gast",
    "PHOTOS TAKEN BY GUEST:": "FOTO'S GENOMEN DOOR GAST:",
    "Photos Taken By Guest": "Foto's Genomen Door Gast",
    "Loved by Travelers Worldwide": "Geliefd bij reizigers wereldwijd",
    "Based on 1,480+ verified reviews": "Gebaseerd op 1.480+ geverifieerde beoordelingen",
    "Authentic Traveler Ratings": "Authentieke Reizigersbeoordelingen",
    "100% Real Guest Experiences": "100% Echte Ervaringen van Gasten",
    "Share Your Story": "Deel Uw Verhaal",
    "Verified Social Proof": "Geverifieerd Bewijs",
    "Discover the World, Perfected For You": "Ontdek de wereld, geperfectioneerd voor jou",
    "The Perfect Stay, Every Single Time": "Het perfecte verblijf, elke keer weer",
    "The Perfect Flight, Every Single Time": "De perfecte vlucht, elke keer weer",
    "Exquisite Luxury, Unrestricted Paths": "Exclusieve luxe, grenzeloze paden",
    "Check-in - Check-out": "Inchecken – Uitchecken",
    "Check In": "Inchecken",
    "Check Out": "Uitchecken",
    "Pick-up Date & Time": "Ophaaldatum & Tijd",
    "Drop-off Date & Time": "Inleverdatum & Tijd",
    "Star Rating": "Aantal sterren",
    "Price Range": "Prijsklasse",
    "Sort By": "Sorteren op",
    "Filter By": "Filteren op",
    "Search Tours": "Zoek tours",
    "Search Hotels": "Zoek hotels",
    "Search Flights": "Zoek vluchten",
    "Search Car Rentals": "Zoek huurauto's",
    "View Details": "Bekijk details",
    "Book Now": "Nu boeken",
    "Reserve Spot": "Plaats reserveren",
    "Select Package": "Selecteer pakket",
    "Custom Itinerary": "Aangepaste reisroute",
    "Passenger Details": "Passagiersgegevens",
    "Contact Details": "Contactgegevens",
    "Payment Method": "Betaalmethode",
    "Credit / Debit Card": "Creditcard / Betaalpas",
    "Bank Transfer": "Bankoverschrijving",
    "Cash on Arrival": "Contant bij aankomst",
    "Instant Confirmation": "Directe bevestiging",
    "Flexible Cancellation": "Flexibel annuleren",
    "Free Cancellation": "Gratis annuleren",
    "All Inclusive": "All Inclusive",
    "Breakfast Included": "Inclusief ontbijt",
    "Free WiFi": "Gratis WiFi",
    "Airport Transfer Included": "Inclusief luchthaventransfer",
    "Private Driver & Guide": "Privéchauffeur & Gids",
    "Luxury Vehicle": "Luxe voertuig",
    "Air Conditioned": "Gekoeld / Airco",
    "Verified Reviews": "Geverifieerde beoordelingen",
    "Customer Support": "Klantenservice",
    "Frequently Asked Questions": "Veelgestelde vragen",
    "Privacy Policy": "Privacybeleid",
    "Terms & Conditions": "Algemene voorwaarden",
    "About Us": "Over ons",
    "Contact Us": "Neem contact op",
    "Home": "Home",
    "Tours": "Tours",
    "Hotels": "Hotels",
    "Flights": "Vluchten",
    "Car Rentals": "Autoverhuur",
    "Rent A Car": "Auto huren",
    "Blog": "Blog",
    "Wishlist": "Verlanglijst",
    "Dashboard": "Dashboard",
    "My Bookings": "Mijn boekingen",
    "Sign In": "Inloggen",
    "Sign Up": "Registreren",
    "Log Out": "Uitloggen"
  },
  ja: {
    "OUR LEGACY": "私たちの伝統",
    "Our Mission & Story": "ミッションとストーリー",
    "Established 2018": "2018年設立",
    "Perfecting Travel Since 2018": "2018年創業・極上の旅を届ける",
    "TRAVELER PHOTOS &": "旅行者の写真と",
    "REVIEWS": "レビュー",
    "ALL REVIEWS": "すべてのレビュー",
    "All Reviews": "すべてのレビュー",
    "WITH PHOTOS": "写真付き",
    "With Photos": "写真付き",
    "HONEYMOON & COUPLES": "ハネムーン＆カップル",
    "Honeymoon & Couples": "ハネムーン＆カップル",
    "FAMILY TRIPS": "ファミリー旅行",
    "Family Trips": "ファミリー旅行",
    "Solo & Wellness": "ソロ＆ウェルネス",
    "SOLO & WELLNESS": "ソロ＆ウェルネス",
    "Verified Guest": "認証済みゲスト",
    "PHOTOS TAKEN BY GUEST:": "ゲストが撮影した写真:",
    "Photos Taken By Guest": "ゲスト撮影写真",
    "Loved by Travelers Worldwide": "世界中の旅行者から愛されています",
    "Based on 1,480+ verified reviews": "1,480件以上の認証済みクチコミに基づく",
    "Authentic Traveler Ratings": "本物の旅行者評価",
    "100% Real Guest Experiences": "100%実在するゲストの体験",
    "Share Your Story": "あなたの体験をシェア",
    "Verified Social Proof": "認証された評判",
    "Discover the World, Perfected For You": "あなたのために完成された世界を発見する",
    "The Perfect Stay, Every Single Time": "毎回完璧な滞在を",
    "The Perfect Flight, Every Single Time": "毎回完璧なフライトを",
    "Exquisite Luxury, Unrestricted Paths": "洗練されたラグジュアリー、自由な旅路",
    "Check-in - Check-out": "チェックイン - チェックアウト",
    "Check In": "チェックイン",
    "Check Out": "チェックアウト",
    "Pick-up Date & Time": "受取日時",
    "Drop-off Date & Time": "返却日時",
    "Star Rating": "星評価",
    "Price Range": "価格帯",
    "Sort By": "並び替え",
    "Filter By": "絞り込み",
    "Search Tours": "ツアーを検索",
    "Search Hotels": "ホテルを検索",
    "Search Flights": "航空券を検索",
    "Search Car Rentals": "レンタカーを検索",
    "View Details": "詳細を見る",
    "Book Now": "今すぐ予約",
    "Reserve Spot": "席を予約",
    "Select Package": "プランを選択",
    "Custom Itinerary": "オーダーメイド旅行日程",
    "Passenger Details": "搭乗者情報",
    "Contact Details": "連絡先情報",
    "Payment Method": "お支払い方法",
    "Credit / Debit Card": "クレジットカード / デビットカード",
    "Bank Transfer": "銀行振込",
    "Cash on Arrival": "現地現金払い",
    "Instant Confirmation": "即時確定",
    "Flexible Cancellation": "柔軟なキャンセルポリシー",
    "Free Cancellation": "キャンセル料無料",
    "All Inclusive": "オールインクルーシブ",
    "Breakfast Included": "朝食付き",
    "Free WiFi": "無料WiFi",
    "Airport Transfer Included": "空港送迎付き",
    "Private Driver & Guide": "専用ドライバー＆ガイド",
    "Luxury Vehicle": "高級車両",
    "Air Conditioned": "エアコン完備",
    "Verified Reviews": "認証済みクチコミ",
    "Customer Support": "カスタマーサポート",
    "Frequently Asked Questions": "よくある質問",
    "Privacy Policy": "プライバシーポリシー",
    "Terms & Conditions": "利用規約",
    "About Us": "会社概要",
    "Contact Us": "お問い合わせ",
    "Home": "ホーム",
    "Tours": "ツアー",
    "Hotels": "ホテル",
    "Flights": "航空券",
    "Car Rentals": "レンタカー",
    "Rent A Car": "レンタカー",
    "Blog": "ブログ",
    "Wishlist": "お気に入り",
    "Dashboard": "ダッシュボード",
    "My Bookings": "予約履歴",
    "Sign In": "ログイン",
    "Sign Up": "新規登録",
    "Log Out": "ログアウト"
  },
  zh: {
    "OUR LEGACY": "我们的传承",
    "Our Mission & Story": "我们的使命与故事",
    "Established 2018": "成立于 2018 年",
    "Perfecting Travel Since 2018": "自 2018 年起追求完美旅行",
    "TRAVELER PHOTOS &": "游客照片与",
    "REVIEWS": "评价",
    "ALL REVIEWS": "所有评价",
    "All Reviews": "所有评价",
    "WITH PHOTOS": "带图评价",
    "With Photos": "带图评价",
    "HONEYMOON & COUPLES": "蜜月与情侣",
    "Honeymoon & Couples": "蜜月与情侣",
    "FAMILY TRIPS": "亲子家庭游",
    "Family Trips": "亲子家庭游",
    "Solo & Wellness": "单人与康养",
    "SOLO & WELLNESS": "单人与康养",
    "Verified Guest": "已验证住客",
    "PHOTOS TAKEN BY GUEST:": "住客实拍照片:",
    "Photos Taken By Guest": "住客实拍照片",
    "Loved by Travelers Worldwide": "深受全球旅行者喜爱",
    "Based on 1,480+ verified reviews": "基于 1,480+ 条真实评价",
    "Authentic Traveler Ratings": "真实游客评分",
    "100% Real Guest Experiences": "100% 真实住客体验",
    "Share Your Story": "分享您的旅行故事",
    "Verified Social Proof": "真实口碑认证",
    "Discover the World, Perfected For You": "探索世界，为您量身打造",
    "The Perfect Stay, Every Single Time": "每一次都是完美的住宿体验",
    "The Perfect Flight, Every Single Time": "每一次都是完美的航班体验",
    "Exquisite Luxury, Unrestricted Paths": "尊贵奢华，畅行无阻",
    "Check-in - Check-out": "入住 – 退房",
    "Check In": "入住",
    "Check Out": "退房",
    "Pick-up Date & Time": "取车日期与时间",
    "Drop-off Date & Time": "还车日期与时间",
    "Star Rating": "星级评定",
    "Price Range": "价格区间",
    "Sort By": "排序方式",
    "Filter By": "筛选条件",
    "Search Tours": "搜索旅游行程",
    "Search Hotels": "搜索酒店",
    "Search Flights": "搜索机票",
    "Search Car Rentals": "搜索租车",
    "View Details": "查看详情",
    "Book Now": "立即预订",
    "Reserve Spot": "预订名额",
    "Select Package": "选择套餐",
    "Custom Itinerary": "定制行程",
    "Passenger Details": "乘客信息",
    "Contact Details": "联系方式",
    "Payment Method": "支付方式",
    "Credit / Debit Card": "信用卡 / 借记卡",
    "Bank Transfer": "银行转账",
    "Cash on Arrival": "到达后现金支付",
    "Instant Confirmation": "即时确认",
    "Flexible Cancellation": "灵活取消",
    "Free Cancellation": "免费取消",
    "All Inclusive": "全包式服务",
    "Breakfast Included": "含早餐",
    "Free WiFi": "免费无线网络",
    "Airport Transfer Included": "含接送机服务",
    "Private Driver & Guide": "私人司机兼导游",
    "Luxury Vehicle": "豪华车型",
    "Air Conditioned": "配备空调",
    "Verified Reviews": "真实评价",
    "Customer Support": "客户服务",
    "Frequently Asked Questions": "常见问题",
    "Privacy Policy": "隐私政策",
    "Terms & Conditions": "条款与条件",
    "About Us": "关于我们",
    "Contact Us": "联系我们",
    "Home": "首页",
    "Tours": "旅游行程",
    "Hotels": "酒店",
    "Flights": "机票",
    "Car Rentals": "租车服务",
    "Rent A Car": "汽车租赁",
    "Blog": "博客文章",
    "Wishlist": "心愿单",
    "Dashboard": "控制面板",
    "My Bookings": "我的预订",
    "Sign In": "登录",
    "Sign Up": "注册",
    "Log Out": "退出登录"
  },
  ru: {
    "OUR LEGACY": "НАШЕ НАСЛЕДИЕ",
    "Our Mission & Story": "Наша миссия и история",
    "Established 2018": "Основано в 2018 году",
    "Perfecting Travel Since 2018": "Совершенствуем путешествия с 2018 года",
    "TRAVELER PHOTOS &": "ФОТО ПУТЕШЕСТВЕННИКОВ И",
    "REVIEWS": "ОТЗЫВЫ",
    "ALL REVIEWS": "ВСЕ ОТЗЫВЫ",
    "All Reviews": "Все отзывы",
    "WITH PHOTOS": "С ФОТО",
    "With Photos": "С фото",
    "HONEYMOON & COUPLES": "МЕДОВЫЙ МЕСЯЦ И ПАРЫ",
    "Honeymoon & Couples": "Медовый месяц и пары",
    "FAMILY TRIPS": "СЕМЕЙНЫЕ ПОЕЗДКИ",
    "Family Trips": "Семейные поездки",
    "Solo & Wellness": "Соло и Велнес",
    "SOLO & WELLNESS": "СОЛО И ВЕЛНЕС",
    "Verified Guest": "Проверенный гость",
    "PHOTOS TAKEN BY GUEST:": "ФОТОГРАФИИ, СДЕЛАННЫЕ ГОСТЕМ:",
    "Photos Taken By Guest": "Фотографии, сделанные гостем",
    "Loved by Travelers Worldwide": "Любимо путешественниками по всему миру",
    "Based on 1,480+ verified reviews": "На основе 1480+ проверенных отзывов",
    "Authentic Traveler Ratings": "Подлинные оценки путешественников",
    "100% Real Guest Experiences": "100% реальный опыт гостей",
    "Share Your Story": "Поделитесь своей историей",
    "Verified Social Proof": "Проверенные отзывы гостей",
    "Discover the World, Perfected For You": "Откройте мир, созданный специально для вас",
    "The Perfect Stay, Every Single Time": "Идеальное проживание каждый раз",
    "The Perfect Flight, Every Single Time": "Идеальный перелет каждый раз",
    "Exquisite Luxury, Unrestricted Paths": "Изысканная роскошь, безграничные возможности",
    "Check-in - Check-out": "Заезд – Выезд",
    "Check In": "Заезд",
    "Check Out": "Выезд",
    "Pick-up Date & Time": "Дата и время получения",
    "Drop-off Date & Time": "Дата и время возврата",
    "Star Rating": "Звездный рейтинг",
    "Price Range": "Диапазон цен",
    "Sort By": "Сортировать по",
    "Filter By": "Фильтровать по",
    "Search Tours": "Искать туры",
    "Search Hotels": "Искать отели",
    "Search Flights": "Искать авиабилеты",
    "Search Car Rentals": "Искать авто в аренду",
    "View Details": "Посмотреть детали",
    "Book Now": "Забронировать сейчас",
    "Reserve Spot": "Зарезервировать место",
    "Select Package": "Выбрать пакет",
    "Custom Itinerary": "Индивидуальный маршрут",
    "Passenger Details": "Данные пассажиров",
    "Contact Details": "Контактные данные",
    "Payment Method": "Способ оплаты",
    "Credit / Debit Card": "Кредитная / Дебетовая карта",
    "Bank Transfer": "Банковский перевод",
    "Cash on Arrival": "Оплата наличными по прибытии",
    "Instant Confirmation": "Мгновенное подтверждение",
    "Flexible Cancellation": "Гибкая отмена",
    "Free Cancellation": "Бесплатная отмена",
    "All Inclusive": "Все включено",
    "Breakfast Included": "Завтрак включен",
    "Free WiFi": "Бесплатный Wi-Fi",
    "Airport Transfer Included": "Трансфер из аэропорта включен",
    "Private Driver & Guide": "Личный водитель и гид",
    "Luxury Vehicle": "Автомобиль премиум-класса",
    "Air Conditioned": "С кондиционером",
    "Verified Reviews": "Проверенные отзывы",
    "Customer Support": "Служба поддержки",
    "Frequently Asked Questions": "Часто задаваемые вопросы",
    "Privacy Policy": "Политика конфиденциальности",
    "Terms & Conditions": "Условия и положения",
    "About Us": "О нас",
    "Contact Us": "Связаться с нами",
    "Home": "Главная",
    "Tours": "Туры",
    "Hotels": "Отели",
    "Flights": "Авиабилеты",
    "Car Rentals": "Аренда авто",
    "Rent A Car": "Аренда авто",
    "Blog": "Блог",
    "Wishlist": "Избранное",
    "Dashboard": "Личный кабинет",
    "My Bookings": "Мои бронирования",
    "Sign In": "Войти",
    "Sign Up": "Регистрация",
    "Log Out": "Выйти"
  },
  hi: {
    "OUR LEGACY": "हमारी विरासत",
    "Our Mission & Story": "हमारा मिशन और कहानी",
    "Established 2018": "2018 में स्थापित",
    "Perfecting Travel Since 2018": "2018 से बेहतरीन यात्रा का अनुभव",
    "TRAVELER PHOTOS &": "यात्रियों की तस्वीरें और",
    "REVIEWS": "समीक्षाएं",
    "ALL REVIEWS": "सभी समीक्षाएं",
    "All Reviews": "सभी समीक्षाएं",
    "WITH PHOTOS": "तस्वीरों के साथ",
    "With Photos": "तस्वीरों के साथ",
    "HONEYMOON & COUPLES": "हनीमून और जोड़े",
    "Honeymoon & Couples": "हनीमून और जोड़े",
    "FAMILY TRIPS": "पारिवारिक यात्राएं",
    "Family Trips": "पारिवारिक यात्राएं",
    "Solo & Wellness": "सोलो और वेलनेस",
    "SOLO & WELLNESS": "सोलो और वेलनेस",
    "Verified Guest": "सत्यापित अतिथि",
    "PHOTOS TAKEN BY GUEST:": "अतिथि द्वारा ली गई तस्वीरें:",
    "Photos Taken By Guest": "अतिथि द्वारा ली गई तस्वीरें",
    "Loved by Travelers Worldwide": "दुनिया भर के यात्रियों द्वारा पसंद किया गया",
    "Based on 1,480+ verified reviews": "1,480+ सत्यापित समीक्षाओं के आधार पर",
    "Authentic Traveler Ratings": "प्रामाणिक यात्री रेटिंग",
    "100% Real Guest Experiences": "100% वास्तविक अतिथि अनुभव",
    "Share Your Story": "अपनी कहानी साझा करें",
    "Verified Social Proof": "सत्यापित सामाजिक प्रमाण",
    "Discover the World, Perfected For You": "दुनिया की खोज करें, आपके लिए बेहतरीन रूप से तैयार की गई",
    "The Perfect Stay, Every Single Time": "हर बार एकदम सही प्रवास",
    "The Perfect Flight, Every Single Time": "हर बार एकदम सही उड़ान",
    "Exquisite Luxury, Unrestricted Paths": "उत्कृष्ट लक्जरी, असीमित रास्ते",
    "Check-in - Check-out": "चेक-इन – चेक-आउट",
    "Check In": "चेक-इन",
    "Check Out": "चेक-आउट",
    "Pick-up Date & Time": "पिक-अप की तारीख और समय",
    "Drop-off Date & Time": "ड्रॉप-ऑफ की तारीख और समय",
    "Star Rating": "स्टार रेटिंग",
    "Price Range": "मूल्य सीमा",
    "Sort By": "क्रमानुसार छांटें",
    "Filter By": "फ़िल्टर करें",
    "Search Tours": "टूर खोजें",
    "Search Hotels": "होटल खोजें",
    "Search Flights": "उड़ानें खोजें",
    "Search Car Rentals": "कार किराए पर खोजें",
    "View Details": "विवरण देखें",
    "Book Now": "अभी बुक करें",
    "Reserve Spot": "स्थान सुरक्षित करें",
    "Select Package": "पैकेज चुनें",
    "Custom Itinerary": "कस्टम यात्रा योजना",
    "Passenger Details": "यात्री का विवरण",
    "Contact Details": "संपर्क विवरण",
    "Payment Method": "भुगतान का तरीका",
    "Credit / Debit Card": "क्रेडिट / डेबिट कार्ड",
    "Bank Transfer": "बैंक ट्रांसफर",
    "Cash on Arrival": "आगमन पर नकद भुगतान",
    "Instant Confirmation": "तत्काल पुष्टि",
    "Flexible Cancellation": "लचीला रद्दीकरण",
    "Free Cancellation": "मुफ्त रद्दीकरण",
    "All Inclusive": "ऑल इंक्लूसिव",
    "Breakfast Included": "नाश्ता शामिल है",
    "Free WiFi": "मुफ्त वाई-फाई",
    "Airport Transfer Included": "एयरपोर्ट ट्रांसफर शामिल",
    "Private Driver & Guide": "निजी ड्राइवर और गाइड",
    "Luxury Vehicle": "लक्जरी वाहन",
    "Air Conditioned": "वातानुकूलित",
    "Verified Reviews": "सत्यापित समीक्षाएं",
    "Customer Support": "ग्राहक सहायता",
    "Frequently Asked Questions": "अक्सर पूछे जाने वाले प्रश्न",
    "Privacy Policy": "गोपनीयता नीति",
    "Terms & Conditions": "नियम और शर्तें",
    "About Us": "हमारे बारे में",
    "Contact Us": "संपर्क करें",
    "Home": "होम",
    "Tours": "टूर",
    "Hotels": "होटल",
    "Flights": "उड़ानें",
    "Car Rentals": "कार किराया",
    "Rent A Car": "कार किराए पर लें",
    "Blog": "ब्लॉग",
    "Wishlist": "विशलिस्ट",
    "Dashboard": "डैशबोर्ड",
    "My Bookings": "मेरी बुकिंग",
    "Sign In": "साइन इन करें",
    "Sign Up": "साइन अप करें",
    "Log Out": "लॉग आउट करें"
  }
};

function translateText(key, lang) {
  if (phraseDict[lang] && phraseDict[lang][key]) {
    return phraseDict[lang][key];
  }

  // Pure numbers/symbols
  if (/^[\d\s\.\,\+\-\/\:\%\$\€\£\$\(\)]+$/.test(key)) {
    return key;
  }

  return key;
}

for (const lang of langs) {
  const srcPath = path.join(srcLocalesDir, `${lang}.json`);
  const pubPath = path.join(pubLocalesDir, `${lang}.json`);

  let dict = {};
  if (fs.existsSync(srcPath)) {
    dict = JSON.parse(fs.readFileSync(srcPath, 'utf8'));
  }

  let updated = 0;
  for (const k of allKeys) {
    const val = dict[k];
    if (phraseDict[lang] && phraseDict[lang][k]) {
      dict[k] = phraseDict[lang][k];
      updated++;
    }
  }

  const jsonStr = JSON.stringify(dict, null, 2);
  fs.writeFileSync(srcPath, jsonStr, 'utf8');
  fs.writeFileSync(pubPath, jsonStr, 'utf8');
  console.log(`[${lang}] Updated explicit phrase dictionary keys in src and public locales.`);
}

console.log('Finished full language translation update!');
